apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: bilalkhandevse/microservices-vendormarketplace-cart-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_url
                  name: config-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_server_address
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "cart-service-svc"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cart-db-cm
                  key: hostname

#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "250m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-svc
spec:
  selector:
    app: cart-service
  ports:
    - port: 80
      targetPort: 8086
