apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: "http://eureka-0.eureka:8761/eureka/"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  bootstrap_servers: "kafka-service:9092"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
data:
  hostname: "redis"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-cm
data:
  email_username: <email-username>
  email_password: <email-app-password>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-cm
data:
  api-gateway-url: "http://127.0.0.1:62198"
#  url fetch minikube service api-gateway-svc --url (using ingress #in future)

