apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "optional:configserver:http://config-server-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: http://eureka-0.eureka:8761/eureka/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  bootstrap_servers: "kafka-service:9092"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
data:
  hostname: "redis-0.redis"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-cm
data:
  email_username: <my-username>
  email_password: <my_app_password>

