apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: bilalkhandevse/microservices-vendormarketplace-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_url
                  name: config-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_server_address
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "payment-service-svc"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: payment-db-cm
                  key: hostname
            - name: BASE_UR
              valueFrom:
                configMapKeyRef:
                  name: payment-service-cm
                  key: api-gateway-url
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: bootstrap_servers

#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "250m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8089
