apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: bilalkhandevse/microservices-vendormarketplace-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_server_address

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: hostname

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: hostname

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: bootstrap_servers

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8088
