spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:2007}
  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29093}
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/payment-service-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:khan}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  success-url: ${BASE_URL:http://localhost:8089}/api/v2/webhook/stripe/success
  cancel-url: ${BASE_URL:http://localhost:8089}/api/v2/webhook/stripe/cancel


server:
  port: 8089

