spring:
  application:
    name: home-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:2007}
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGODB_URL:mongodb://admin:password123@localhost:27019/home-service-db?authSource=admin}

server:
  port: 8091