apiVersion: v1
kind: PersistentVolume
metadata:
  name: review-wishlist-db-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/review-wishlist-db-postgres"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-wishlist-db-postgres-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: review-wishlist-db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-wishlist-db-postgres
  serviceName: review-wishlist-db-postgres-headless
  template:
    metadata:
      labels:
        app: review-wishlist-db-postgres
    spec:
      containers:
        - name: review-wishlist-db-postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: POSTGRES_DB
              value: "review-wishlist-service-db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: review-wishlist-db-postgres-storage
              mountPath: /var/lib/postgresql/data  # ← stores data here
      volumes:
        - name: review-wishlist-db-postgres-storage
          persistentVolumeClaim:
            claimName: review-wishlist-db-postgres-pvc  # ← Points to PVC

---
apiVersion: v1
kind: Service
metadata:
  name: review-wishlist-db-postgres-headless
spec:
  clusterIP: None
  selector:
    app: review-wishlist-db-postgres
  ports:
    - port: 5437
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: review-wishlist-db-cm
data:
  hostname: "review-wishlist-db-postgres-0.review-wishlist-db-postgres-headless"


