services:
  postgres:
    image: postgres:15
    container_name: microservice-vendor_marketplace-user-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  default:
    external:
      name: auth-service_kafka-network
