services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # user service
  user-service:
    image: bilalkhandevse/microservices-vendormarketplace-user-service:latest
    container_name: user-service
    environment:
      SPRING_PROFILE_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-server:2007
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9093
      DB_HOST: microservice-vendor_marketplace-user-service-postgres
    ports:
      - "8080:8080"
    networks:
      - vendor-marketplace-microservices-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  vendor-marketplace-microservices-network:
    driver: bridge
