services:
  mongodb:
    image: mongo:8.0
    container_name: product_query_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: product-query-service-db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: