spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v2/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v2/user/**

            - id: seller-service
              uri: lb://SELLER-SERVICE
              predicates:
                - Path=/api/v2/seller/**

            - id: product-command-service
              uri: lb://PRODUCT-COMMAND-SERVICE
              predicates:
                - Path=/api/v2/products/command/**

            - id: product-query-service
              uri: lb://PRODUCT-QUERY-SERVICE
              predicates:
                - Path=/api/v2/products/**

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/v2/carts/**

            - id: transaction-report-service
              uri: lb://TRANSACTION-REPORT-SERVICE
              predicates:
                - Path=/api/v2/transactions/**
                - Path=/api/v2/admin/tr/**
                - Path=/api/v2/reports/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 2008

jwt:
  secret:
    key: 6pQm/8nXkz1uD0mU5wXrZ4qV9rG7dJk8aLfP9nQw1yZ2xThB9cN4qR5vY7uK3mP0
