spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5436/payment-service-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:khan}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51SWhU9As5ybJL7ryX9VyNefH2Kl8VbxjcFXaMc0U9m9k3NMLwwEgVRepwuSFiZilO0v4WOp2OFrpt29gThlu3F8800NJeE7unm} # Add default empty value
  success-url: ${BASE_URL:http://localhost:8089}/api/v2/webhook/stripe/success
  cancel-url: ${BASE_URL:http://localhost:8089}/api/v2/webhook/stripe/cancel

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

server:
  port: 8089

