spring:
  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:27018/product-query-service-db?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      group-id: product-query-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

server:
  port: 8085