spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5437/review-wishlist-service-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:khan}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

feign:
  client:
    product-query-service:
      url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

server:
  port: 8090