spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user-service-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:khan}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

admin:
  info:
    name: ${ADMIN_NAME:Bilal Khan}
    email: ${ADMIN_EMAIL:anonymousalwaysalone@gmail.com}
    mobile: ${ADMIN_MOBILE:03001233445}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

server:
  port: 8080
